import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Navbar from "../components/NavBar";
import Testimonials from "../components/Testimonials";
import ContactUs from "../components/Contact_Us_Form";
import Services from "../components/Services";
import Head from "next/head";
import {Box} from "@chakra-ui/react";
import { useRef } from "react";

const Home = () => {
  return (
    <Box bgColor="#0c0c0c" color={'white'}>
      <Head>
        <title>Las Secuelas Group Ltd.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Hero/>
      <Services/>
      <Testimonials/>
      <ContactUs/>
      <Footer/>
    </Box>
  );
};

export default Home;
